---
# Source: showks-portal-frontend/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: showks-portal-frontend
  namespace: showks
  labels:
    app: showks-portal-frontend
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: app-port
  selector:
    app: showks-portal-frontend

---
# Source: showks-portal-frontend/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: showks-portal-frontend
  namespace: showks
  labels:
    app: showks-portal-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: showks-portal-frontend
  template:
    metadata:
      labels:
        app: showks-portal-frontend
    spec:
      containers:
        - name: showks-portal-frontend
          image: gcr.io/ipc-cloudnativedays/showks-portal-frontend:prod-8127c25f7cf3148593d93bab2f5d66e82bad1167
          env:
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: showks-config
                  key: domain
            - name: AGGREGATOR_URL
              value: https://aggregator$(DOMAIN)
          ports:
            - name: app-port
              containerPort: 3000
              protocol: TCP

